const genresByMood = {
    euphoric: [
      'A Cappella',
      'Accordion',
      'Afrobeat',
      'Afrobeats',
      'Aussietronica',
      'Balearic',
      'Barnemusikk',
      'Barnmusik',
      'Big Band',
      'Bossa Nova',
      'Brazilian Composition',
      'Brazilian Gospel',
      'Brazilian Pop Music',
      'Bubble Trance',
      'Bubblegum Dance',
      'Bubblegum Pop',
      'C64',
      'Cabaret',
      'Calypso',
      'Candy Pop',
      'Cantautor',
      'Cante Flamenco',
      'Capoeira',
      'Carnatic',
      'Catstep',
      'Caucasian Folk',
      'Ceilidh',
      'Celtic',
      'Celtic Christmas',
      'Chamber Pop',
      'Chaotic Hardcore',
      'Chicago House',
      'Chicano Rap',
      'Chiptune',
      'Classic Funk Rock',
      'Country Road',
      'Dance Pop',
      'Dance Rock',
      'Danish Pop Rock',
      'Deep Full On',
      "Deep Melodic House",
      "Deep Progressive House",
      "Deep Progressive Trance",
      "Deep Uplifting Trance",
      "Eurobeat",
      "Eurodance",
      "Europop",
      "Eurovision",
      "Folk-pop",
      "Future Ambient",
      "Future Garage",
      "Futurepop",
      "G Funk",
      "Garage Pop",
      "Happy Hardcore",
      "Italo Dance",
      "Italo House",
      "J-Pop",
      "K-Pop",
      "Nu Disco",
      "Nu Skool Breaks",
      "Old Skool Hardcore",
      "Power Metal",
      "Rave",
      "Synthpop",
      "Trance",
      "Tribal House",
      "Uplifting Trance",
      'Happy Hardcore',
      'Highlife',
      'Gospel',
      'Gospel Blues',
      'Gospel Reggae',
      'Hands Up',
      'Hi Nrg',
      'J-pop',
      'J-poprock',
      'J-poppunk',
      'J-poprock',
      'J-rap',
      'J-indie',
      'J-dance',
      'J-core',
      'J-alt',
      'Jump Up',
      'Jumpstyle',
      'Jungle',
      'K-pop',
      'J-indie',
      'K-hop',
      'K-indie',
      'K-rock',
      'Kabarett',
      'Karneval',
      'Kiwi Rock',
      'Kizomba',
      'Kompa',
      'Kindermusik',
      'Kirtan',
      'Latvian Pop',
    'Lounge House',
    'Mambo',
    'Mariachi',
    'Merengue',
    'Merengue Urbano',
    'Miami Bass',
    'Moombahton',
    'Motivation',
    'Motown',
    'New Jack Swing',
    'New Orleans Jazz',
    'Nu Disco',
    'Nueva Cancion',
    'Oshare Kei',
    'P Funk',
    'P Funk',
    'Pop',
    'Pop Christmas',
    'Pop House',
    'Pop Rock',
    'Popgaze',
    'Psychedelic Trance',
    'Ska',
    'Soca',
    'Soul',
    'Soul Flow',
    'Soul Jazz',
    'South African Jazz',
    "Swing",
    "Surf Music",
    "Sunset Lounge",
    "Tango",
    "Tropical",
    "Twee Pop",
    "Twee Indie Pop",
    "Uplifting Trance",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Tango",
    "Vintage Western",
    "Vintage Jazz",
    "Vintage Schlager",
    "Vocal House",
    "Visual Kei",
    "Vienna Indie",
    "Vintage Chanson",
    "Vintage Rockabilly",
    "Vocal Jazz",
    "Viral Pop",
    "Vocaloid",
    "Vegas Indie",
    "Ukulele",
    "Texas Country",
    "Thai Pop",
    "Teen Pop",
    "Synthpop",
    "Swedish Pop",
    "Swedish Synthpop",
    "Swedish Soft Pop",
    "Swedish Pop Punk",
    "Swedish Punk",
    "Swedish Prog",
    "Swedish Reggae",
    "Swiss Rock",
    "Swiss Hip Hop",
    "Swiss Folk",
    "Swedish Indie Pop",
    "Turkish Pop",
    "Turkish Rock",
    "Turkish Jazz",
    "Turkish Hip Hop",
    "Turkish Folk",
    "Turkish Classical",
    "Turkish Alternative",
    "Tribute",
    "Traditional Ska",
    "Traditional Swing",
    "Traditional Soul",
    "Traditional Reggae",
    "Traditional Rock 'N Roll",
    "Traditional Rockabilly",
    "Traditional Scottish Folk",
    "Traditional Irish Folk",
    "Traditional Funk",
    "Traditional Folk",
    "Traditional Country",
    "Traditional British Folk",
    "Traditional Blues",
    "Traditional Funk",
    "Talent Show",
    "Taiwanese Pop",
    "Tropical",
    "Trova",
    "Turntablism",
    "Trash Rock",
    "Triangle Indie",
    "Trip Hop",
    "Turbo Folk",
    "Tzadik",
    "Uk Dub",
    "Uk Garage",
    "Uk Hip Hop",
    "Uk Post-punk",
    "Ukrainian Rock",
    "Underground Pop Rap",
    "Underground Power Pop",
    "Underground Rap",
    "Vapor House",
    "Vintage Gospel",
    "Vintage Country Folk",
    "Underground Hip Hop",
    "Underground Latin Hip Hop",
    "Unblack Metal",
    "Ukulele",
    "Underground Power Pop",
    "Underground Pop Rap",
    "Underground Rap",
    "Visual Kei",
    "Vocal House",
    "Vocal Jazz",
    "Vocaloid",
    "Vintage Chanson",
    "Vintage Country Folk",
    "Vintage Gospel",
    "Vintage Jazz",
    "Vintage Reggae",
    "Vintage Rockabilly",
    "Vintage Schlager",
    "Vintage Swedish Pop",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Tango",
    "Vintage Western",
    "Violin",
    "Viral Pop",
    "Vocal House",
    "Vocal Jazz",
    "Vocaloid",
    "Volksmusik",
    "Warm Drone",
    "West Coast Rap",
    "Western Swing",
    "Wind Ensemble",
    "World Chill",
    "World Christmas",
    "World Fusion",
    "Wrock",
    "Wonky",
    "Ye Ye",
    "Yoik",
    "Zeuhl"
    ],
    sad: [
      'Acoustic Blues',
      'Adult Standards',
      'Albanian Pop',
      'Alternative Country',
      'Ballad',
      'Bolero',
      'Blues',
      'Blues-rock',
      'Blues-rock Guitar',
      'Brazilian Punk',
      'British Blues',
      'Broadway',
      'Cajun',
      'Canadian Country',
      'Canadian Pop',
      'Carnatic',
      'Caucasian Folk',
      'Chanson',
      'Chanson Quebecois',
      'Chicago Blues',
      'Chillstep',
      'Classic Psychedelic Rock',
      'Country Blues',
      'Dark Ambient',
      'Dark Black Metal',
      'Death Metal',
      'Deep Chill',
      'Deep Indie Singer-songwriter',
      "Depressive Black Metal",
      "Depressive Black Metal",
      "Desert Blues",
      "Dream Pop",
      "Dreamo",
      "Downtempo",
      "Downtempo Fusion",
      "Downtempo Trip Hop",
      "Emo",
      "Emo Punk",
      "Funeral Doom",
      "Gothic Metal",
      "Gothic Rock",
      "Grunge",
      "Indie Rock",
      "Lament",
      "Metalcore",
      "Neofolk",
      "Post-Hardcore",
      "Post-Rock",
      "Sadcore",
      "Shoegaze",
      "Slowcore",
      'Gothic Doom',
    'Gothic Metal',
    'Gothic Post-punk',
    'Gothic Rock',
    'Gothic Symphonic Metal',
    'Grisly Death Metal',
    'Goregrind',
    'Grim Death Metal',
    'Glitch',
    'Glitch Beats',
    'Glitch Hop',
    'Grime',
    'Grindcore',
    'Groove Metal',
    'Grunge',
    'Grunge Pop',
    'Gypsy Jazz',
    'Hauntology',
    'Horror Punk',
    'Horrorcore',
    'Industrial',
    'Industrial Metal',
    'Industrial Rock',
    'Indie Emo',
    'Indie Emo Rock',
    'Illbient',
    'Jazz Blues',
    'Jazz Fusion',
    'Jazz Metal',
    'Jazz Orchestra',
    'Jump Blues',
    'Melancholia',
    'Modern Downshift',
    'Neo Mellow',
    'Neo Soul',
    'Neo Soul-jazz',
    'Nordic Folk',
    'Norwegian Gospel',
    'Norwegian Punk',
    'Piano Blues',
    'Sadcore',
    'Screamo',
    'Screamo Punk',
    'Screamocore',
    'Slow Core',
    'Southern Soul Blues',
    "Stoner Metal",
    "Stoner Rock",
    "Straight Edge",
    "Street Punk",
    "Sunset Lounge",
    "Suomi Rock",
    "Swamp Blues",
    "Swamp Pop",
    "Swedish Soft Pop",
    "Swedish Synthpop",
    "Swedish Pop Punk",
    "Swedish Prog",
    "Swedish Punk",
    "Swedish Reggae",
    "Swirl Psych",
    "Swedish Metal",
    "Swedish Jazz",
    "Swedish Indie Rock",
    "Swedish Indie Pop",
    "Swedish Hard Rock",
    "Swedish Hip Hop",
    "Swedish Alternative Rock",
    "Synthpop",
    "Surf Music",
    "Sunset Lounge",
    "Symphonic Rock",
    "Symphonic Metal",
    "Symphonic Black Metal",
    "Swiss Rock",
    "Swiss Hip Hop",
    "Swiss Folk",
    "Street Punk",
    "Straight Edge",
    "Stoner Rock",
    "Stoner Metal",
    "Stomp Pop",
    "Stomp And Whittle",
    "Stomp And Holler",
    "Stomp And Flutter",
    "Steelpan",
    "Steampunk",
    "Spytrack",
    "Spoken Word",
    "Speedcore",
    "Speed Metal",
    "Speed Garage",
    "Spanish Reggae",
    "Spanish Punk",
    "Spanish Pop Rock"
    ],
    peaceful: [
      'Abstract',
      'Abstract Beats',
      'Acoustic Pop',
      'Ambient',
      'Ambient Fusion',
      'Ambient Trance',
      'Andean',
      'Appalachian Folk',
      'Athens Indie',
      'Avant-garde Jazz',
      'Barnemusikk',
      'Barnmusik',
      'Baroque',
      'Bay Area Hip Hop',
      'Belgian Indie',
      'Belgian Rock',
      'Brazilian Indie',
      'British Folk',
      'Broken Beat',
      'Brooklyn Indie',
      'C-pop',
      'C64',
      'C86',
      'Cantautor',
      'Cante Flamenco',
      'Celtic',
      'Celtic Christmas',
      'Chamber Pop',
      'Chill Groove',
      'Chill Lounge',
      'Chill-out',
      'Chill-out Trance',
      'Chillwave',
      'Classical Guitar',
      'Country Dawn',
      'Deep Acoustic Pop',
      "Deep Ambient",
      "Deep Chill",
      "Deep Lounge",
      "Deep Smooth Jazz",
      "Deep Sunset Lounge",
      "Folk",
      "Folk Christmas",
      "Folk Metal",
      "Folk Rock",
      "New Age",
      "New Age Piano",
      "Relaxative",
      "Relaxative Piano",
      "Soundtrack",
      "Space Ambient",
      "Space Rock",
      "World",
      'Gospel',
    'Gospel Blues',
    'Gospel Reggae',
    'Guidance',
    'Healing',
    'Harp',
    'Hawaiian',
    'Hindustani Classical',
    'Hungarian Rock',
    'Hungarian Hip Hop',
    'Hip Hop Quebecois',
    'Hip Hop Tuga',
    'House',
    'Instrumental Post Rock',
    'Indie Dream Pop',
    'Indie Folk',
    'Indie Pop',
    'Indie Pop Rock',
    'Indie Shoegaze',
    'Indie Singer-songwriter',
    'Irish Folk',
    'Irish Indie',
    'Irish Rock',
    'Iskelma',
    'Italian Jazz',
    'Jazz',
    'Jazz Bass',
    'Jazz Trio',
    'Jangle Pop',
    'Jangle Rock',
    'Jazz Christmas',
    'Jug Band',
    'Jump Up',
    'Light Music',
    'Meditation',
    'Minimal',
    'Minimal Dub',
    'Minimal Dubstep',
    'Minimal Melodic Techno',
    'Minimal Tech House',
    'Minimal Techno',
    'Minimal Wave',
    'Morna',
    'Musica Para Ninos',
    'Musiikkia Lapsille',
    'Musique Concrete',
    'Musique Pour Enfants',
    'Muziek Voor Kinderen',
    'New Age',
    'New Age Piano',
    'New Wave Pop',
    'New Weird America',
    'Nordic House',
    'Pipe Band',
    'Polynesian Pop',
    'Pop Punk',
    'Progressive Trance',
    'Progressive Uplifting Trance',
    'Quiet Storm',
    'Shoegaze',
    'Singer-songwriter',
    'Smooth Jazz',
    'Smooth Urban R&b',
    'Soundtrack',
    "String Band",
    "String Folk",
    "String Quartet",
    "Substep",
    "Swedish Soft Pop",
    "Swedish Synthpop",
    "Swing",
    "Synthpop",
    "Surf Music",
    "Sunset Lounge",
    "Swiss Folk",
    "Swiss Hip Hop",
    "Swiss Rock",
    "Suomi Rock",
    "Sunset Lounge",
    "Swirl Psych",
    "Symphonic Rock",
    "Symphonic Metal",
    "Symphonic Black Metal",
    "Swedish Jazz",
    "Swedish Indie Rock",
    "Swedish Indie Pop",
    "Swedish Hard Rock",
    "Swedish Hip Hop",
    "Swedish Alternative Rock",
    "String Folk",
    "String Quartet",
    "Substep",
    "Spytrack",
    "Spoken Word",
    "Speed Garage",
    "Steelpan",
    "Stomp Pop",
    "Stomp And Whittle",
    "Stomp And Holler",
    "Stomp And Flutter",
    "Swedish Soft Pop",
    "Swedish Synthpop",
    "Sunset Lounge",
    "Steampunk",
    "Spanish Reggae"
    ],
    dramatic: [
      'Abstract Hip Hop',
      'Alternative Metal',
      'Alternative Metalcore',
      'Alternative R&b',
      'Ambient Dub Techno',
      'Ambient Idm',
      'Anarcho-punk',
      'Art Rock',
      'Atmospheric Black Metal',
      'Atmospheric Post Rock',
      'Atmospheric Post-metal',
      'Black Death',
      'Black Metal',
      'Black Sludge',
      'Black Thrash',
      'Blackgaze',
      'Brutal Death Metal',
      'Brutal Deathcore',
      'Chaotic Black Metal',
      'Chaotic Hardcore',
      'Chicago Blues',
      'Cinematic Dubstep',
      'Dark Cabaret',
      'Death Core',
      'Deep Deep Tech House',
      'Deep East Coast Hip Hop',
      'Deep Indie Rock',
      'Deep Psytrance',
      'Deep Techno',
      'Deep Wave',
      'Deepstep',
      "Doom Metal",
      "Drone",
      "Drone Metal",
      "Drone Psych",
      "Dub Techno",
      "Dubstep",
      "Dubsteppe",
      "Experimental",
      "Experimental Dubstep",
      "Experimental Psych",
      "Experimental Rock",
      "Heavy Metal",
      "Industrial Metal",
      "Industrial Rock",
      "Noise",
      "Power Electronics",
      "Power Noise",
      "Progressive Metal",
      "Symphonic Metal",
      "Technical Death Metal",
      "Thrash Metal",
      'Hardcore',
      'Hardcore Breaks',
      'Hardcore Hip Hop',
      'Hardcore Punk',
      'Hardcore Techno',
      'Hardstyle',
      'Horror Punk',
      'Horrorcore',
      'Industrial',
      'Industrial Metal',
      'Industrial Rock',
      'Intelligent Dance Music',
      'Jazz Funk',
      'Jazz Fusion',
      'Jazz Metal',
      'Jazz Orchestra',
      'Jerk',
      'Jungle',
      'J-core',
      'J-theme',
      'Kraut Rock',
      'Kuduro',
      'Kurdish Folk',
      'Kwaito',
      'La Indie',
      'Laboratorio',
      'Martial Industrial',
      'Math Rock',
      'Mathcore',
      'Medieval',
      'Medieval Rock',
      'Modern Classical',
      'Neo Classical Metal',
      'Neo-progressive',
      'Neo-psychedelic',
      'Noise',
      'Noise Punk',
      'Noise Rock',
      'Orchestral',
      'Outlaw Country',
      'Pagan Black Metal',
      'Progressive Metal',
      'Power Metal',
      'Raw Black Metal',
      'Slam Death Metal',
      'Sleaze Rock',
      'Southern Hip Hop',
      "Thrash Core",
    "Thrash Metal",
    "Thrash-groove Metal",
    "Traditional Ska",
    "Traditional Soul",
    "Traditional Swing",
    "Traditional Reggae",
    "Traditional Rock 'N Roll",
    "Traditional Rockabilly",
    "Traditional Scottish Folk",
    "Traditional Irish Folk",
    "Traditional Funk",
    "Traditional Folk",
    "Traditional Country",
    "Traditional British Folk",
    "Traditional Blues",
    "Traditional Funk",
    "Technical Brutal Death Metal",
    "Technical Death Metal",
    "Techno",
    "Tibetan",
    "Tico",
    "Timba",
    "Tin Pan Alley",
    "Thrash Metal",
    "Thrash Core",
    "Thrash-groove Metal",
    "Traditional Ska",
    "Traditional Soul",
    "Traditional Swing",
    "Traditional Reggae",
    "Traditional Rock",
    "Thrash Core",
    "Thrash Metal",
    "Thrash-groove Metal",
    "Traditional Ska",
    "Traditional Soul",
    "Traditional Swing",
    "Traditional Reggae",
    "Traditional Rock 'N Roll",
    "Traditional Rockabilly",
    "Traditional Scottish Folk",
    "Traditional Irish Folk",
    "Traditional Funk",
    "Traditional Folk",
    "Traditional Country",
    "Traditional British Folk",
    "Traditional Blues",
    "Traditional Funk",
    "Technical Brutal Death Metal",
    "Technical Death Metal",
    "Techno",
    "Tibetan",
    "Tico",
    "Timba",
    "Tin Pan Alley",
    "Thrash Metal",
    "Thrash Core",
    "Thrash-groove Metal",
    "Traditional Ska",
    "Traditional Soul",
    "Traditional Swing",
    "Traditional Reggae",
    "Traditional Rock 'N Roll",
    "Traditional Rockabilly",
    "Traditional Scottish Folk",
    "Traditional Irish Folk",
    "Traditional Funk",
    "Traditional Folk",
    "Traditional Country",
    "Traditional British Folk",
    "Traditional Blues",
    "Technical Brutal Death Metal",
    "Technical Death Metal",
    "Techno",
    "Terrorcore",
    "Texas Blues",
    "Texas Country",
    "Thai Indie",
    "Tibetan",
    "Tico",
    "Timba",
    "Tin Pan Alley",
    "Trance",
    "Trance Hop",
    "Traditional Funk",
    "Traditional Folk",
    "Traditional Country",
    "Traditional British Folk",
    "Traditional Blues",
    "Terrorcore",
    "Texas Blues",
    "Texas Country",
    "Thai Indie",
    "Trance",
    "Trance Hop",
    "Tekno",
    "Throat Singing"
    ],
    romantic: [
      'Acousmatic',
      'African Percussion',
      'African Rock',
      'Afrikaans',
      'Ambient Psychill',
      'Anime',
      'Anime Score',
      'Ballad',
      'Baroque Ensemble',
      'Bebop',
      'Bluegrass',
      'Blues',
      'Bossa Nova Jazz',
      'Brazilian Hip Hop',
      'Brega',
      'Broadway',
      'Canterbury Scene',
      'Cantopop',
      'Canzone Napoletana',
      'Chamber Pop',
      'Christian Dance',
      'Christian Metal',
      'Classic Italian Pop',
      'Classic Russian Rock',
      'Contemporary Jazz',
      'Cowboy Western',
      'Dance-punk',
      'Deep Funk House',
      "Deep Vocal House",
      "Deep Vocal Jazz",
      "Doo-wop",
      "Dream Pop",
      "Easy Listening",
      "Electro Swing",
      "Love Metal",
      "Lovecore",
      "Lover's Rock",
      "Slow Jam",
      "Smooth Jazz",
      "Soul",
      "Soul Jazz",
      'Gauze Pop',
      'Girl Group',
      'Glitter Trance',
      'Gothic Alternative',
      'Gothic Americana',
      'Gothic Post-punk',
      'Groove Metal',
      'Grunge Pop',
      'Hard Glam',
      'Hard Trance',
      'Harmonica Blues',
      'Haunted House',
      'Hawaiian',
      'Hip Pop',
      'Indie Pop Rock',
      'Indie R&b',
      'Indie Rock',
      'Indie Shoegaze',
      'Industrial Rock',
      'Italian Disco',
      'Italian Folk',
      'Italian Pop',
      'Italian Pop Rock',
      'Italian Punk',
      'Italo Dance',
      'J-pop',
      'J-rock',
      'Jazz Blues',
      'Jazz Funk',
      'Jazz Fusion',
      'Jazz Orchestra',
      'Jangle Pop',
      'Jangle Rock',
      'Liedermacher',
      'Louisiana Blues',
      'Lovers Rock',
      'Neo Romantic',
      'Neo-singer-songwriter',
      'Nepali',
      'Norwegian Jazz',
      'Operatic Pop',
      'Orquesta Tipica',
      'Orquesta Tropical',
      'Romantic',
      'Pop Emo',
      'Punk Blues',
      'Rock Steady',
      'Rumba',
      'Russian Pop',
      'Salsa',
      'Samba',
      'Soul Blues',
      "Vintage Tango",
    "Vintage Western",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Reggae",
    "Vintage Rockabilly",
    "Vintage Schlager",
    "Vintage Swedish Pop",
    "Venezuelan Rock",
    "Video Game Music",
    "Vintage Chanson",
    "Vietnamese Pop",
    "Vintage Country Folk",
    "Vintage Gospel",
    "Vintage Jazz",
    "Violin",
    "Vintage Western",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Tango",
    "Vintage Chanson",
    "Vintage Country Folk",
    "Vintage Gospel",
    "Vintage Jazz",
    "Vintage Reggae",
    "Vintage Rockabilly",
    "Vintage Schlager",
    "Vintage Swedish Pop",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Tango",
    "Venezuelan Rock",
    "Video Game Music",
    "Vietnamese Pop",
    "Vintage Western",
    "Vintage Swing",
    "Vintage Swoon",
    "Vintage Tango",
    "Violin",
    "Vocal House",
    "Vocal Jazz",
    "Vocaloid",
    "Volksmusik",
    "Warm Drone",
    "Welsh Rock",
    "West African Jazz",
    "Western Swing"
    ]
  };
  
// For this function we need to take a playlist of songs and extract information from them in order to return a vibe. 
// Information taken in:
// genre -- sorted into moods in database
// have a count variable for amount of tracks in a playlist
// create a string variable for final vibe
// create variables for all moods and add up all moods from all tracks 
// compare moods and add most common mood to final vibe string
// create variable for and  add up the danceability, energy and valence of every track, then dvide to get average
// danceability(float number, how fun a song is to dance to ) -- 0.0-1.0
// energy(float number, how much energy is in a song) -- 0.0-1.0
// if danceability and energy > 0.5 
//     return forceful + vibe
// if danceability and energy < 0.5
//     return calm + vibe
// valence(float number, how happy a song is) -- 0.0-1.0
// if valence > 0.5
//     return positive
// Define the API URL

const genreArray = ["Violin", "Suomi Rock","Steampunk", "Vocaloid"];

function generateMood(genresByMood, genreArray){ 
  const moodCount = {
    'euphoric': 0,
    'sad': 0,
    'peaceful': 0,
    'dramatic': 0,
    'romantic': 0
  };
  genreArray.forEach((item, index) => {
    for (let [mood, genres] of Object.entries(genresByMood)) {
      if (genres.includes(item)) {
        moodCount[mood] ++; // Return the mood (key) if the genre is found in its array
      }
    };
  });
  let maxMood = '';
  let maxCount = -1;
  for (let [mood, count] of Object.entries(moodCount)) {
    if (count > maxCount) {
      maxCount = count;
      maxMood = mood;
    }
  }
  console.log(maxMood);
};
generateMood(genresByMood, genreArray);

//make api 
function boosters(playlistJson,username){
    var playlistCount= playlistJson.limit

    for (i=0;i<playlistCount;i++){
        var valence = 
        var danceability = 
        var energy = 
        var id=playlistJson.items[i].id
        var name=playlistJson.items[i].name
        var img=playlistJson.items[i].images[0].url
        var mood
    }
  }

// computeFeatures(playlistFeatures) {
//   let averageFeatures = {
//     danceability: 0,
//     energy: 0,
//     valence: 0,
//   };
//   playlistFeatures.forEach((track) => {
//     for (let key in track) {
//       if (key !== "id") {
//         averageFeatures[key] += track[key];
//       }
//     }
//   });
//   for (let key in averageFeatures) {
//     averageFeatures[key] =
//       Math.round(
//         ((averageFeatures[key] * 100) / playlistFeatures.length +
//           Number.EPSILON) *
//           100
//       ) / 100;
//   };
// };