INSERT INTO dummy_playlists (playlist_id, playlist_owner, playlist_name, playlist_img, mood_name, mood_percent) VALUES
(1, 'John Doe', 'Euphoric Vibes', 'http://example.com/euphoric1.jpg', 'euphoric', 77),
(2, 'Jane Smith', 'Euphoria Unleashed', 'http://example.com/euphoric2.jpg', 'euphoric', 87),
(3, 'Emma Johnson', 'Euphoric Tunes', 'http://example.com/euphoric3.jpg', 'euphoric', 45),
(4, 'James Brown', 'Dramatic Beats', 'http://example.com/dramatic1.jpg', 'dramatic', 68),
(5, 'Olivia Davis', 'Drama Queen', 'http://example.com/dramatic2.jpg', 'dramatic', 99),
(6, 'Michael Miller', 'Dramatic Rhythms', 'http://example.com/dramatic3.jpg', 'dramatic', 56),
(7, 'Emily Wilson', 'Romantic Melodies', 'http://example.com/romantic1.jpg', 'romantic', 88),
(8, 'David Moore', 'Romance in the Air', 'http://example.com/romantic2.jpg', 'romantic', 56),
(9, 'Sophia Taylor', 'Romantic Serenade', 'http://example.com/romantic3.jpg', 'romantic', 98),
(10, 'Daniel Anderson', 'Unique Beats', 'http://example.com/unique1.jpg', 'unique', 96),
(11, 'Mia Thomas', 'Uniquely Yours', 'http://example.com/unique2.jpg', 'unique', 56),
(12, 'Jackson Jackson', 'Unique Rhythms', 'http://example.com/unique3.jpg', 'unique', 34),
(13, 'Lucas White', 'Sad Melodies', 'http://example.com/sad1.jpg', 'sad', 76),
(14, 'Ella Harris', 'Tears in Rain', 'http://example.com/sad2.jpg', 'sad', 86),
(15, 'Aiden Lewis', 'Melancholic Rhythms', 'http://example.com/sad3.jpg', 'sad', 46);